fix: bring pypi publish back to original release workflow

diff --git a/.github/workflows/_build-wheel-release-upload.yml b/.github/workflows/_build-wheel-release-upload.yml
--- a/.github/workflows/_build-wheel-release-upload.yml
+++ b/.github/workflows/_build-wheel-release-upload.yml
@@ -126,7 +126,6 @@ jobs:
         with:
           prerelease: true
           generate_release_notes: true
-          draft: true
           token: ${{ secrets.GITHUB_TOKEN }}
 
   github-release:
@@ -155,7 +154,43 @@ jobs:
         with:
           body_path: CHANGELOG.txt
           token: ${{ secrets.GITHUB_TOKEN }}
-          draft: true
+
+  pypi-publish:
+    needs: [github-pre-release, github-release]
+    runs-on: ubuntu-latest
+    if: always()  # This job will always initiate regardless of the success or failure of the needed jobs
+    steps:
+      - name: Fail pypi-publish job if github-(pre)-release job failed
+        run: |
+          if [ "${{ needs.github-pre-release.result }}" == 'success' ] || [ "${{ needs.github-release.result }}" == 'success' ]; then
+            echo "Ready for PyPI release..."
+          else
+            echo "Previous github-(pre)-release job failed; exiting..."
+            exit 1
+          fi
+
+      - uses: actions/download-artifact@v4
+        with:
+          pattern: '**/*' # Make sure all files are downloaded, including wheels
+          path: dist
+          merge-multiple: true
+
+      - name: Setup Python for PyPI upload
+        uses: actions/setup-python@v5
+        with:
+          python-version: '3.13'
+
+      - name: Install Twine
+        run: |
+          python -m pip install --upgrade pip
+          pip install twine
+
+      - name: Publish package to PyPI
+        env:
+          TWINE_USERNAME: __token__
+          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
+        run: |
+          twine upload dist/* --verbose
 
   docs:
     needs: [github-pre-release, github-release]
